server:
  port: 8084

spring:
  datasource:
    initialization-mode: always
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=cashtest
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    open-in-view: false
    generate-ddl: true
    properties:
      javax:
        persistence:
          schema-generation:
            database:
              action: create
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        generate_statistics: false
        jdbc:
          fetch_size: 2000
          lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        ddl-auto: create-drop
        hbm2dll:
          auto: create
          create_namespaces: true
        default_schema: cashtest

logging:
  level:
    '[org.springframework.data]': TRACE
    '[org.hibernate]': TRACE
    '[javax.persistence]': TRACE
